//
//  AvaMeters.swift
//  Ava
//
//  Created by James Lubowich on 10/20/15.
//  Copyright (c) 2015 com.JLubo.Ava. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class AvaMeters : NSObject {

    //// Cache

    private struct Cache {
        static var growthColor: UIColor = UIColor(red: 0.031, green: 0.416, blue: 0.165, alpha: 1.000)
        static var growthLight: UIColor = AvaMeters.growthColor.colorWithHighlight(0.8)
    }

    //// Colors

    public class var growthColor: UIColor { return Cache.growthColor }
    public class var growthLight: UIColor { return Cache.growthLight }

    //// Drawing Methods

    public class func drawMeter(frame frame: CGRect, wheelColor: UIColor, angle: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let highlight = wheelColor.colorWithHighlight(0.3)
        let shadow = wheelColor.colorWithShadow(0.5)
        let backgroundColor = UIColor(red: 0.238, green: 0.238, blue: 0.238, alpha: 1.000)

        //// Gradient Declarations
        let wheelGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [wheelColor.CGColor, UIColor.whiteColor().CGColor], [0, 1])


        //// Subframes
        let progressBackground: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.05694 + 0.5), frame.minY + floor(frame.height * 0.05036 + 0.5), floor(frame.width * 0.94662 + 0.5) - floor(frame.width * 0.05694 + 0.5), floor(frame.height * 0.94964 + 0.5) - floor(frame.height * 0.05036 + 0.5))


        //// Progress Background
        //// Highlights Drawing
        var highlightsPath = UIBezierPath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.25000 * progressBackground.width, progressBackground.minY + 0.06699 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.37059 * progressBackground.width, progressBackground.minY + 0.01704 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.28784 * progressBackground.width, progressBackground.minY + 0.04514 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.32838 * progressBackground.width, progressBackground.minY + 0.02835 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.25000 * progressBackground.width, progressBackground.minY + 0.06699 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.06699 * progressBackground.width, progressBackground.minY + 0.25000 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.14645 * progressBackground.width, progressBackground.minY + 0.14645 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.08884 * progressBackground.width, progressBackground.minY + 0.21216 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.11555 * progressBackground.width, progressBackground.minY + 0.17734 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.06699 * progressBackground.width, progressBackground.minY + 0.25000 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.00000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.01704 * progressBackground.width, progressBackground.minY + 0.37059 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.00000 * progressBackground.width, progressBackground.minY + 0.45630 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.00573 * progressBackground.width, progressBackground.minY + 0.41280 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.00000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.06699 * progressBackground.width, progressBackground.minY + 0.75000 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.01704 * progressBackground.width, progressBackground.minY + 0.62941 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.04514 * progressBackground.width, progressBackground.minY + 0.71216 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.02835 * progressBackground.width, progressBackground.minY + 0.67162 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.06699 * progressBackground.width, progressBackground.minY + 0.75000 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.25000 * progressBackground.width, progressBackground.minY + 0.93301 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.14645 * progressBackground.width, progressBackground.minY + 0.85355 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.21216 * progressBackground.width, progressBackground.minY + 0.91116 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.17734 * progressBackground.width, progressBackground.minY + 0.88445 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.25000 * progressBackground.width, progressBackground.minY + 0.93301 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 1.00000 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.37059 * progressBackground.width, progressBackground.minY + 0.98296 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.45630 * progressBackground.width, progressBackground.minY + 1.00000 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.41280 * progressBackground.width, progressBackground.minY + 0.99427 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 1.00000 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.75000 * progressBackground.width, progressBackground.minY + 0.93301 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.62941 * progressBackground.width, progressBackground.minY + 0.98296 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.71216 * progressBackground.width, progressBackground.minY + 0.95486 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.67162 * progressBackground.width, progressBackground.minY + 0.97165 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.75000 * progressBackground.width, progressBackground.minY + 0.93301 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.93301 * progressBackground.width, progressBackground.minY + 0.75000 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.85355 * progressBackground.width, progressBackground.minY + 0.85355 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.91116 * progressBackground.width, progressBackground.minY + 0.78784 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.88445 * progressBackground.width, progressBackground.minY + 0.82266 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.93301 * progressBackground.width, progressBackground.minY + 0.75000 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 1.00000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.98296 * progressBackground.width, progressBackground.minY + 0.62941 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 1.00000 * progressBackground.width, progressBackground.minY + 0.54370 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.99427 * progressBackground.width, progressBackground.minY + 0.58720 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 1.00000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.93301 * progressBackground.width, progressBackground.minY + 0.25000 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.98296 * progressBackground.width, progressBackground.minY + 0.37059 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.95486 * progressBackground.width, progressBackground.minY + 0.28784 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.97165 * progressBackground.width, progressBackground.minY + 0.32838 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.93301 * progressBackground.width, progressBackground.minY + 0.25000 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.75000 * progressBackground.width, progressBackground.minY + 0.06699 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.85355 * progressBackground.width, progressBackground.minY + 0.14645 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.78784 * progressBackground.width, progressBackground.minY + 0.08884 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.82266 * progressBackground.width, progressBackground.minY + 0.11555 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.75000 * progressBackground.width, progressBackground.minY + 0.06699 * progressBackground.height))
        highlightsPath.closePath()
        highlightsPath.moveToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.00000 * progressBackground.height))
        highlightsPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.62941 * progressBackground.width, progressBackground.minY + 0.01704 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.54370 * progressBackground.width, progressBackground.minY + 0.00000 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.58720 * progressBackground.width, progressBackground.minY + 0.00573 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        highlightsPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.00000 * progressBackground.height))
        highlightsPath.closePath()
        highlight.setFill()
        highlightsPath.fill()


        //// Shaded Drawing
        var shadedPath = UIBezierPath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.37059 * progressBackground.width, progressBackground.minY + 0.01704 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.00000 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.41280 * progressBackground.width, progressBackground.minY + 0.00573 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.45630 * progressBackground.width, progressBackground.minY + 0.00000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.37059 * progressBackground.width, progressBackground.minY + 0.01704 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.14645 * progressBackground.width, progressBackground.minY + 0.14645 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.25000 * progressBackground.width, progressBackground.minY + 0.06699 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.17734 * progressBackground.width, progressBackground.minY + 0.11555 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.21216 * progressBackground.width, progressBackground.minY + 0.08884 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.14645 * progressBackground.width, progressBackground.minY + 0.14645 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.01704 * progressBackground.width, progressBackground.minY + 0.37059 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.06699 * progressBackground.width, progressBackground.minY + 0.25000 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.02835 * progressBackground.width, progressBackground.minY + 0.32838 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.04514 * progressBackground.width, progressBackground.minY + 0.28784 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.01704 * progressBackground.width, progressBackground.minY + 0.37059 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.01704 * progressBackground.width, progressBackground.minY + 0.62941 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.00000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.00573 * progressBackground.width, progressBackground.minY + 0.58720 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.00000 * progressBackground.width, progressBackground.minY + 0.54370 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.01704 * progressBackground.width, progressBackground.minY + 0.62941 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.14645 * progressBackground.width, progressBackground.minY + 0.85355 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.06699 * progressBackground.width, progressBackground.minY + 0.75000 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.11555 * progressBackground.width, progressBackground.minY + 0.82266 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.08884 * progressBackground.width, progressBackground.minY + 0.78784 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.14645 * progressBackground.width, progressBackground.minY + 0.85355 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.37059 * progressBackground.width, progressBackground.minY + 0.98296 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.25000 * progressBackground.width, progressBackground.minY + 0.93301 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.32838 * progressBackground.width, progressBackground.minY + 0.97165 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.28784 * progressBackground.width, progressBackground.minY + 0.95486 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.37059 * progressBackground.width, progressBackground.minY + 0.98296 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.62941 * progressBackground.width, progressBackground.minY + 0.98296 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 1.00000 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.58720 * progressBackground.width, progressBackground.minY + 0.99427 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.54370 * progressBackground.width, progressBackground.minY + 1.00000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.62941 * progressBackground.width, progressBackground.minY + 0.98296 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.85355 * progressBackground.width, progressBackground.minY + 0.85355 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.75000 * progressBackground.width, progressBackground.minY + 0.93301 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.82266 * progressBackground.width, progressBackground.minY + 0.88445 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.78784 * progressBackground.width, progressBackground.minY + 0.91116 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.85355 * progressBackground.width, progressBackground.minY + 0.85355 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.98296 * progressBackground.width, progressBackground.minY + 0.62941 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.93301 * progressBackground.width, progressBackground.minY + 0.75000 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.97165 * progressBackground.width, progressBackground.minY + 0.67162 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.95486 * progressBackground.width, progressBackground.minY + 0.71216 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.98296 * progressBackground.width, progressBackground.minY + 0.62941 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.98296 * progressBackground.width, progressBackground.minY + 0.37059 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 1.00000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.99427 * progressBackground.width, progressBackground.minY + 0.41280 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 1.00000 * progressBackground.width, progressBackground.minY + 0.45630 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.98296 * progressBackground.width, progressBackground.minY + 0.37059 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.85355 * progressBackground.width, progressBackground.minY + 0.14645 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.93301 * progressBackground.width, progressBackground.minY + 0.25000 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.88445 * progressBackground.width, progressBackground.minY + 0.17734 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.91116 * progressBackground.width, progressBackground.minY + 0.21216 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.85355 * progressBackground.width, progressBackground.minY + 0.14645 * progressBackground.height))
        shadedPath.closePath()
        shadedPath.moveToPoint(CGPointMake(progressBackground.minX + 0.62941 * progressBackground.width, progressBackground.minY + 0.01704 * progressBackground.height))
        shadedPath.addCurveToPoint(CGPointMake(progressBackground.minX + 0.75000 * progressBackground.width, progressBackground.minY + 0.06699 * progressBackground.height), controlPoint1: CGPointMake(progressBackground.minX + 0.67162 * progressBackground.width, progressBackground.minY + 0.02835 * progressBackground.height), controlPoint2: CGPointMake(progressBackground.minX + 0.71216 * progressBackground.width, progressBackground.minY + 0.04514 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.50000 * progressBackground.width, progressBackground.minY + 0.50000 * progressBackground.height))
        shadedPath.addLineToPoint(CGPointMake(progressBackground.minX + 0.62941 * progressBackground.width, progressBackground.minY + 0.01704 * progressBackground.height))
        shadedPath.closePath()
        shadow.setFill()
        shadedPath.fill()




        //// Progress Slider Drawing
        var progressSliderRect = CGRectMake(frame.minX + floor(frame.width * 0.05694 + 0.5), frame.minY + floor(frame.height * 0.05036 + 0.5), floor(frame.width * 0.94662 + 0.5) - floor(frame.width * 0.05694 + 0.5), floor(frame.height * 0.94964 + 0.5) - floor(frame.height * 0.05036 + 0.5))
        var progressSliderPath = UIBezierPath()
        progressSliderPath.addArcWithCenter(CGPointMake(progressSliderRect.midX, progressSliderRect.midY), radius: progressSliderRect.width / 2, startAngle: -angle * CGFloat(M_PI)/180, endAngle: -90 * CGFloat(M_PI)/180, clockwise: true)
        progressSliderPath.addLineToPoint(CGPointMake(progressSliderRect.midX, progressSliderRect.midY))
        progressSliderPath.closePath()

        backgroundColor.setFill()
        progressSliderPath.fill()


        //// Meter Face Drawing
        let meterFaceRect = CGRectMake(frame.minX + floor(frame.width * 0.10676 + 0.5), frame.minY + floor(frame.height * 0.10072 + 0.5), floor(frame.width * 0.89680 + 0.5) - floor(frame.width * 0.10676 + 0.5), floor(frame.height * 0.89928 + 0.5) - floor(frame.height * 0.10072 + 0.5))
        var meterFacePath = UIBezierPath(ovalInRect: meterFaceRect)
        CGContextSaveGState(context)
        meterFacePath.addClip()
        CGContextDrawLinearGradient(context, wheelGradient,
            CGPointMake(meterFaceRect.midX, meterFaceRect.minY),
            CGPointMake(meterFaceRect.midX, meterFaceRect.maxY),
            .DrawsBeforeStartLocation)
        CGContextRestoreGState(context)
    }

    public class func drawCheckmark() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(4, 4, 35, 35))
        UIColor.grayColor().setFill()
        ovalPath.fill()


        //// Rectangle Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 13.51, 19.49)
        CGContextRotateCTM(context, 45 * CGFloat(M_PI) / 180)

        let rectanglePath = UIBezierPath(rect: CGRectMake(0, 0, 12.28, 4.96))
        UIColor.blueColor().setFill()
        rectanglePath.fill()

        CGContextRestoreGState(context)


        //// Rectangle 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 16, 27.17)
        CGContextRotateCTM(context, -45 * CGFloat(M_PI) / 180)

        let rectangle2Path = UIBezierPath(rect: CGRectMake(0, 0, 19.21, 4.83))
        UIColor.blueColor().setFill()
        rectangle2Path.fill()

        CGContextRestoreGState(context)
    }

    public class func drawCanvas1(frame frame: CGRect) {

        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 30, frame.minY + 32, 75, 64))
        UIColor.grayColor().setFill()
        ovalPath.fill()
    }

}



extension UIColor {
    func colorWithHue(newHue: CGFloat) -> UIColor {
        var saturation: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(nil, saturation: &saturation, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: newHue, saturation: saturation, brightness: brightness, alpha: alpha)
    }
    func colorWithSaturation(newSaturation: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: nil, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: hue, saturation: newSaturation, brightness: brightness, alpha: alpha)
    }
    func colorWithBrightness(newBrightness: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: nil, alpha: &alpha)
        return UIColor(hue: hue, saturation: saturation, brightness: newBrightness, alpha: alpha)
    }
    func colorWithAlpha(newAlpha: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, brightness: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: nil)
        return UIColor(hue: hue, saturation: saturation, brightness: brightness, alpha: newAlpha)
    }
    func colorWithHighlight(highlight: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-highlight) + highlight, green: green * (1-highlight) + highlight, blue: blue * (1-highlight) + highlight, alpha: alpha * (1-highlight) + highlight)
    }
    func colorWithShadow(shadow: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-shadow), green: green * (1-shadow), blue: blue * (1-shadow), alpha: alpha * (1-shadow) + shadow)
    }
}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
